version: "3.9"

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: book
      MYSQL_USER: spring-user
      MYSQL_PASSWORD: spring-secret
    ports:
      - "3306:3306"

  # Spring Boot Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    depends_on: 
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/book?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Bangkok
      SPRING_DATASOURCE_USERNAME: spring-user
      SPRING_DATASOURCE_PASSWORD: spring-secret
    restart: on-failure
