name: Build & Test on CICD Merge

on:
  push:
    branches:
      - cicd   # 👈 trigger เฉพาะเมื่อมีการ push หรือ merge เข้า branch cicd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run Tests
        run: mvn test
